### ISSUE TITLE
Example plugin broken?

### ISSUE THREAD

**Issue by burdoto** [TyrenDe/streamdeck-client-csharp#1]
i am at the end of all wisdom.
i have basically copied (https://github.com/burdoto/VBAN-StreamDeck-Plugin/blob/master/VBANDeck/Plugin.cs) the example plugin startup code (https://github.com/TyrenDe/streamdeck-client-csharp/blob/master/TestPlugin/Program.cs) and the plugin is STILL CRASHING on startup.
i dont know what to do at this point, if you see anything that could help, please tell me
![rider64_2019-01-19_09-10-08](https://user-images.githubusercontent.com/42473485/51424342-921a8280-1bcc-11e9-9cca-8fafd18eb1bd.png)

**Comment by TyrenDe** [comment]
I'm just about to head to bed. I'll try to help you when I get time tomorrow. I'd guess you have a missing dependency. You can try running in a debugger. Also, copy all the output files over.

**Comment by burdoto** [comment]
okay, thanks for the heads up. i will await your response.

**Comment by burdoto** [comment]
NOTE that i am using NetCore2.2

**Comment by TyrenDe** [comment]
Oh, that may help. Did you try cloning my project directly and using the SLN provided? I haven't tested with .NET Core 2.2 yet. I'll test now.

**Comment by TyrenDe** [comment]
Can you share a zip of the plugin you are copying in? Just zip the entire: "com..." folder. Put it somewhere and link to me?

**Comment by TyrenDe** [comment]
I just tested it (Windows 10) and it worked fine.  Make sure you are packaging it correctly? And you are grabbing ALL of the files.   My folder I copied in has like 226 files or something like that.l

**Comment by burdoto** [comment]
1) My Plugin is available in its whole at https://github.com/burdoto/VBAN-StreamDeck-Plugin
2) I mean, i saw only one .CS file so I didnt mind copying something else.

**Comment by TyrenDe** [comment]
Okay, here is the problem, you need to copy EVERYTHING in this folder: `copy "A:\Workspaces\VBAN-StreamDeck-Plugin\VBANDeck\bin\Release\netcoreapp2.2\win10-x64\VBANDeck.exe" "../build/de.kaleidox.vbandeck.sdPlugin/"` Not just the EXE.  All of the files in there are required.  And there are a lot, like over 200 of them.
Try coping everything in the: `VBAN-StreamDeck-Plugin\VBANDeck\bin\Debug\netcoreapp2.2\win10-x64\publish` folder.

**Comment by burdoto** [comment]
This fixed the issue. Thanks! <3
