### ISSUE TITLE
Needs updating...

### ISSUE THREAD

**Issue by tinodo** [TyrenDe/streamdeck-client-csharp#21]
This is project still maintained?

It's been a while since it was updated. At least update the references and, for example, the DeviceType enum. As per documentation: Possible values are kESDSDKDeviceType_StreamDeck (0), kESDSDKDeviceType_StreamDeckMini (1), kESDSDKDeviceType_StreamDeckXL (2), kESDSDKDeviceType_StreamDeckMobile (3), kESDSDKDeviceType_CorsairGKeys (4), kESDSDKDeviceType_StreamDeckPedal (5), kESDSDKDeviceType_CorsairVoyager (6), and kESDSDKDeviceType_StreamDeckPlus (7).

Now, it only shows the first 2.

There are some other relatively small changes between the current version (https://developer.elgato.com/documentation/stream-deck/sdk/overview/) and what is in the library.

**Comment by BarRaider** [comment]
The new SDK was just released a few days ago. I'll make an update soon with the new updates, and update the DeviceType too
