### ISSUE TITLE
Context Value of button

### ISSUE THREAD

**Issue by rawat94** [TyrenDe/streamdeck-client-csharp#7]
Hi 
Is there a way to get the context value of all the buttons at the starting of the application ?
so that I can store it in dictionary using its UUID and context value

**Comment by TyrenDe** [comment]
To be honest, I haven't touched this stuff in a long time.  I do know, you can only get info about buttons that belong to your plug-in.  So, you can't get "all buttons", unless all buttons are from your plug-in.  Then, I think you would just need to listen to the will appear event and that'll tell you about each button as they show up.
